feat: move to esm
sindresorhus/globby pull request #181
Opened 2021-07-16 20:27 UTC by antongolub

* add named exports
* update all deps to the latest versions
* add Node.js v16 to test matrix
* apply xo --fix
* BREAKING CHANGE: require Node.js >= 12.20

2021-07-17 13:55 UTC, sindresorhus commented
Thanks for working on this.

You need to update index.d.ts and the readme for ESM too.

2021-07-17 14:00 UTC, sindresorhus requested changes

2021-07-17 14:00 UTC, sindresorhus commented on index.js
> +// Legacy API
This will be a major release. I don't want to expose the legacy API.

2021-07-17 14:00 UTC, sindresorhus commented on index.js
> +export default globby;
There should not be a default export.

2021-07-17 18:07 UTC, antongolub commented
Let's save `globby` as `globbyAsync` alias.

2021-07-17 19:27 UTC, antongolub commented on index.js
> +export const globby = async (patterns, options) => {
Let's save globby as globbyAsync alias.

2021-07-17 19:51 UTC, sindresorhus commented on bench.js
> +	for (const directory of ['a', 'b']
Move it out into a variable to make it more readable.

2021-07-19 09:58 UTC, antongolub commented
rfr

2021-07-19 18:00 UTC, sindresorhus commented on index.js
> +export const globby = async (patterns, options) => {
I disagree. Aliases cause confusion.

2021-07-19 18:02 UTC, antongolub commented on index.js
> +export const globby = async (patterns, options) => {
Maybe just `globby` and `globbySync`?

2021-07-19 18:02 UTC, sindresorhus commented
I can never decide how to handle named exports with async and sync methods:

- `globby` and `globbySync`
- `globbyAsync` and `globbySync`

The former looks nicer, but the latter is clearer. Any opinion?

2021-07-19 20:05 UTC, antongolub commented
My guess is that for most users, the migration will look like this:
`const globby = require('globby') → import {globbyAsync as globby} from 'globby'`.
Well... I'd prefer just `import {globby} from 'globby'` instead.

2021-07-19 20:29 UTC, sindresorhus commented
Alright. Let's go with `globby` for async and drop `globbyAsync`.

2021-07-21 06:32 UTC, antongolub commented
@sindresorhus, your turn

2021-07-22 01:04 UTC, merged

2021-07-22 17:20 UTC, zloirock commented
@sindresorhus sorry, why do you avoid the default export here?

2021-07-23 03:24 UTC, fisker commented
I guess for consistency import? But I think maybe we can export both named and default? `export {globby as default, globby}`

2021-07-23 23:03 UTC, sindresorhus commented
It's weird to have one default and one named when there are two main exports. I only do default and named export mix when there's only one main export and some secondary exports (like error, or helper utilities).

2021-07-23 23:04 UTC, sindresorhus commented
> But I think maybe we can export both named and default? export {globby as default, globby}

No, there should be only one way to import the thing. Aliases create confusion and inconsistency.